# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpHouse(object):
    def setupUi(self, UpHouse):
        UpHouse.setObjectName("UpHouse")
        UpHouse.setWindowModality(QtCore.Qt.NonModal)
        UpHouse.resize(931, 590)
        UpHouse.setMinimumSize(QtCore.QSize(931, 590))
        UpHouse.setMaximumSize(QtCore.QSize(931, 590))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        UpHouse.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(UpHouse)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.menu_widget = QtWidgets.QWidget(self.splitter)
        self.menu_widget.setMinimumSize(QtCore.QSize(150, 150))
        self.menu_widget.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menu_widget.setFont(font)
        self.menu_widget.setStyleSheet("background-color: #06162d;\n"
"color: #fff;\n"
"border: none;")
        self.menu_widget.setObjectName("menu_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_widget)
        self.gridLayout.setContentsMargins(4, 4, 4, 15)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.menu_widget)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("#toolBox {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#toolBox::tab {\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"\n"
"#toolBox::tab:selected {\n"
"    background-color: #2d9cdb;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#toolBox QPushButton {\n"
"    padding:5px 0px 5px 20px;\n"
"    text-align:left;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#toolBox QPushButton:hover {\n"
"    background-color: #85C1E9;\n"
"}\n"
"\n"
"#toolBox QPushButton:checked {\n"
"    background-color: #3498DB;\n"
"}\n"
"\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setGeometry(QtCore.QRect(0, 0, 172, 481))
        self.home_page.setObjectName("home_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.home_button = QtWidgets.QPushButton(self.home_page)
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_button.setObjectName("home_button")
        self.verticalLayout_4.addWidget(self.home_button)
        spacerItem = QtWidgets.QSpacerItem(20, 191, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/home-4-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.home_page, icon1, "")
        self.Clientes_page = QtWidgets.QWidget()
        self.Clientes_page.setGeometry(QtCore.QRect(0, 0, 172, 481))
        self.Clientes_page.setObjectName("Clientes_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Clientes_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.consultar_alterar = QtWidgets.QPushButton(self.Clientes_page)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.consultar_alterar.setFont(font)
        self.consultar_alterar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.consultar_alterar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.consultar_alterar.setObjectName("consultar_alterar")
        self.verticalLayout_2.addWidget(self.consultar_alterar)
        self.adicionar = QtWidgets.QPushButton(self.Clientes_page)
        self.adicionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar.setObjectName("adicionar")
        self.verticalLayout_2.addWidget(self.adicionar)
        self.remover = QtWidgets.QPushButton(self.Clientes_page)
        self.remover.setObjectName("remover")
        self.verticalLayout_2.addWidget(self.remover)
        spacerItem1 = QtWidgets.QSpacerItem(20, 472, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/group-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.Clientes_page, icon2, "")
        self.boletos_page = QtWidgets.QWidget()
        self.boletos_page.setGeometry(QtCore.QRect(0, 0, 172, 481))
        self.boletos_page.setObjectName("boletos_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.boletos_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gerar = QtWidgets.QPushButton(self.boletos_page)
        self.gerar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gerar.setObjectName("gerar")
        self.verticalLayout_6.addWidget(self.gerar)
        self.cancelar = QtWidgets.QPushButton(self.boletos_page)
        self.cancelar.setObjectName("cancelar")
        self.verticalLayout_6.addWidget(self.cancelar)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/invoice_invoice_ticket_document_icon_188775.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.boletos_page, icon3, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)
        self.main_widget = QtWidgets.QWidget(self.splitter)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.main_widget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("#tabWidget{\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::close-button{\n"
"    margin-left: 3px;\n"
"    image: url(:/icon/icons/x-mark-4-32.ico);\n"
"}\n"
"\n"
"QTabBar::close-button:hover{\n"
"    image :url(:/icon/icons/x-mark-4-48.ico)\n"
"}")
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        UpHouse.setCentralWidget(self.centralwidget)

        self.retranslateUi(UpHouse)
        self.toolBox.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(UpHouse)

    def retranslateUi(self, UpHouse):
        _translate = QtCore.QCoreApplication.translate
        UpHouse.setWindowTitle(_translate("UpHouse", "System Up House"))
        self.home_button.setText(_translate("UpHouse", "Home"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.home_page), _translate("UpHouse", "Home"))
        self.consultar_alterar.setText(_translate("UpHouse", "Consultar/Alterar Cliente"))
        self.adicionar.setText(_translate("UpHouse", "Adicionar Cliente"))
        self.remover.setText(_translate("UpHouse", "Remover Cliente"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Clientes_page), _translate("UpHouse", "Clientes"))
        self.gerar.setText(_translate("UpHouse", "Gerar Boleto"))
        self.cancelar.setText(_translate("UpHouse", "Cancelar Boleto"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.boletos_page), _translate("UpHouse", "Boletos"))
from Front_End.static import resource
