# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(757, 533)
        Form.setMinimumSize(QtCore.QSize(30, 30))
        Form.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 490, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"        border-radius: 12px;\n"
"        border: 2px solid gray;\n"
"        background-color: #101B79;\n"
"        color: white;\n"
"        border-color: #A3A3A3;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #2E3E98; /* Cor de fundo ao passar o mouse */\n"
"    }\n"
"    QPushButton:pressed {\n"
"        border-style: inset; /* Efeito de profundidade ao ser pressionado */\n"
"    }")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Iniciar"))
